import type { MetadataRoute } from "next";

/**
 * PWA-Manifest — Voraussetzung für „Add to Home Screen" auf iOS/Android
 * und damit auch für Web-Push auf iPhone (Web Push funktioniert dort nur
 * in installierter PWA, nicht in normalem Safari-Tab).
 *
 * Icons:
 *  - /icon (512×512 PNG, generated by src/app/icon.tsx)
 *  - /apple-icon (180×180 PNG, generated by src/app/apple-icon.tsx)
 *  - /favicon.svg (skalierbares SVG für moderne Browser)
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Rad der Schande",
    short_name: "Schande",
    description: "Wer trägt die Schande? Lass das Rad entscheiden.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#06140D",
    theme_color: "#06140D",
    categories: ["games", "entertainment", "social"],
    lang: "de",
    icons: [
      {
        src: "/favicon.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "any",
      },
      {
        src: "/icon",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/apple-icon",
        sizes: "180x180",
        type: "image/png",
        purpose: "any",
      },
    ],
  };
}
